// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.0
// source: github.com/dosquad/go-grpcauth/test/simple.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_github_com_dosquad_go_grpcauth_test_simple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dosquad_go_grpcauth_test_simple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_github_com_dosquad_go_grpcauth_test_simple_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Online        bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_github_com_dosquad_go_grpcauth_test_simple_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dosquad_go_grpcauth_test_simple_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_github_com_dosquad_go_grpcauth_test_simple_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Response) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

var File_github_com_dosquad_go_grpcauth_test_simple_proto protoreflect.FileDescriptor

const file_github_com_dosquad_go_grpcauth_test_simple_proto_rawDesc = "" +
	"\n" +
	"0github.com/dosquad/go-grpcauth/test/simple.proto\x12\rgrpcauth.test\"\x0e\n" +
	"\fEmptyRequest\"6\n" +
	"\bResponse\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online2\x8f\x01\n" +
	"\x04Test\x12C\n" +
	"\vTestOffline\x12\x1b.grpcauth.test.EmptyRequest\x1a\x17.grpcauth.test.Response\x12B\n" +
	"\n" +
	"TestOnline\x12\x1b.grpcauth.test.EmptyRequest\x1a\x17.grpcauth.test.ResponseB%Z#github.com/dosquad/go-grpcauth/testb\x06proto3"

var (
	file_github_com_dosquad_go_grpcauth_test_simple_proto_rawDescOnce sync.Once
	file_github_com_dosquad_go_grpcauth_test_simple_proto_rawDescData []byte
)

func file_github_com_dosquad_go_grpcauth_test_simple_proto_rawDescGZIP() []byte {
	file_github_com_dosquad_go_grpcauth_test_simple_proto_rawDescOnce.Do(func() {
		file_github_com_dosquad_go_grpcauth_test_simple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dosquad_go_grpcauth_test_simple_proto_rawDesc), len(file_github_com_dosquad_go_grpcauth_test_simple_proto_rawDesc)))
	})
	return file_github_com_dosquad_go_grpcauth_test_simple_proto_rawDescData
}

var file_github_com_dosquad_go_grpcauth_test_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dosquad_go_grpcauth_test_simple_proto_goTypes = []any{
	(*EmptyRequest)(nil), // 0: grpcauth.test.EmptyRequest
	(*Response)(nil),     // 1: grpcauth.test.Response
}
var file_github_com_dosquad_go_grpcauth_test_simple_proto_depIdxs = []int32{
	0, // 0: grpcauth.test.Test.TestOffline:input_type -> grpcauth.test.EmptyRequest
	0, // 1: grpcauth.test.Test.TestOnline:input_type -> grpcauth.test.EmptyRequest
	1, // 2: grpcauth.test.Test.TestOffline:output_type -> grpcauth.test.Response
	1, // 3: grpcauth.test.Test.TestOnline:output_type -> grpcauth.test.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_dosquad_go_grpcauth_test_simple_proto_init() }
func file_github_com_dosquad_go_grpcauth_test_simple_proto_init() {
	if File_github_com_dosquad_go_grpcauth_test_simple_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dosquad_go_grpcauth_test_simple_proto_rawDesc), len(file_github_com_dosquad_go_grpcauth_test_simple_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_dosquad_go_grpcauth_test_simple_proto_goTypes,
		DependencyIndexes: file_github_com_dosquad_go_grpcauth_test_simple_proto_depIdxs,
		MessageInfos:      file_github_com_dosquad_go_grpcauth_test_simple_proto_msgTypes,
	}.Build()
	File_github_com_dosquad_go_grpcauth_test_simple_proto = out.File
	file_github_com_dosquad_go_grpcauth_test_simple_proto_goTypes = nil
	file_github_com_dosquad_go_grpcauth_test_simple_proto_depIdxs = nil
}
